CREATE VIEW accdatesalessummarykrishikalyantax_view AS
 SELECT DATE_FORMAT(DATENEW, '%Y-%M-%D') AS datenew, SUM(AMOUNT) AS KRISHIKALYANTAX,receipts.ACCOUNTDATE FROM taxlines
 left join receipts on receipts.id=taxlines.receipt
 LEFT JOIN tickets ON taxlines.receipt=tickets.ID
 LEFT JOIN TAXES ON TAXES.ID=TAXLINES.TAXID
 WHERE iscancelticket='N' AND TAXES.NAME LIKE 'KRISHI%'
 group by ACCOUNTDATE;
 

CREATE VIEW billwisekrishikalyantax_view AS
  SELECT RECEIPT AS id,sum(AMOUNT) AS KRISHIKALYANTAX,RECEIPT AS RECEIPT from taxlines
  LEFT JOIN TAXES ON TAXES.ID=TAXLINES.TAXID
  LEFT JOIN tickets ON taxlines.receipt=tickets.ID
  WHERE iscancelticket='N' AND TAXES.NAME LIKE 'KRISHI%'
  group by RECEIPT;

drop view billwisevattax_view;
CREATE VIEW billwisevattax_view AS
  SELECT RECEIPT AS id,sum(AMOUNT) AS TAXAMT,RECEIPT AS RECEIPT from taxlines
  LEFT JOIN TAXES ON TAXES.ID=TAXLINES.TAXID
  LEFT JOIN tickets ON taxlines.receipt=tickets.ID
  WHERE iscancelticket='N' AND  TAXES.NAME NOT LIKE 'Service Tax%' AND
  (TAXES.NAME NOT LIKE 'SWACH%' AND TAXES.NAME NOT LIKE 'SBC%') AND TAXES.NAME NOT LIKE 'KRISHI%'
  group by RECEIPT;

drop view accdatesalessummaryvattax_view;
 CREATE VIEW accdatesalessummaryvattax_view AS
 SELECT DATE_FORMAT(DATENEW, '%Y-%M-%D') AS datenew, SUM(AMOUNT) AS TAXAMT,receipts.ACCOUNTDATE FROM taxlines
 left join receipts on receipts.id=taxlines.receipt
 LEFT JOIN tickets ON taxlines.receipt=tickets.ID
 LEFT JOIN TAXES ON TAXES.ID=TAXLINES.TAXID
 WHERE iscancelticket='N' AND tickets.isnonchargable='N' AND TAXES.NAME NOT LIKE 'Service Tax%' AND (TAXES.NAME NOT LIKE 'SWACH%' 
 AND TAXES.NAME NOT LIKE 'SBC%') AND TAXES.NAME NOT LIKE 'KRISHI%' 
 group by ACCOUNTDATE;


drop view billreport_view;
create view billreport_view as
SELECT UUID() as billreport_view_id, R.DATENEW, 
	TK.TICKETID AS BILLNO,TK.NOOFCOVERS AS PAX, P.NAME AS USER,VT.TAXAMT AS TAX,
	SUM(IF(C1.name = "Food", TL.UNITS*TL.PRICE, 0)) Food,
	SUM(IF(C1.name = "Tobacco", TL.UNITS*TL.PRICE, 0)) Tobacco,
	SUM(IF(C1.name = "Liquor", TL.UNITS*TL.PRICE, 0)) Liquor,
	SUM(IF(C1.name = "Beverage", TL.UNITS*TL.PRICE, 0)) Beverage,
	ST.SERVICETAXAMT, SC.SERVICECHARGEAMT,
	COALESCE(P1.TOTAL,0) AS CASH, COALESCE(P2.TOTAL,0) AS AMEX,
	COALESCE(P3.TOTAL,0) AS CHEQUE, COALESCE(P4.TOTAL,0) AS STAFF, COALESCE(P5.TOTAL,0) AS COMP, 
	COALESCE(P6.TOTAL,0) AS VOUCHER,COALESCE(P7.TOTAL,0) AS MOBILE, TK.ROUNDOFFVALUE, TK.BILLAMOUNT,F.NAME AS  FLOOR,
        SW.SWACHBHARATTAXAMT,TK.TIPS AS TIPS, COALESCE(P8.TOTAL,0) AS VCLOUD, COALESCE(P9.TOTAL,0) AS FOODPANDA,
        COALESCE(P10.TOTAL,0) AS SWIGGY, COALESCE(P11.TOTAL,0) AS DELIVERY,
	COALESCE(P12.TOTAL,0) AS VISA, COALESCE(P13.TOTAL,0) AS OTHERCARDS,COALESCE(P14.TOTAL,0) AS ZOMATO,
        KT.KRISHIKALYANTAX AS KRISHIKALYANTAX
	FROM RECEIPTS R 
	LEFT JOIN PAYMENTS P1 ON P1.RECEIPT=R.ID AND P1.PAYMENT='Cash'
	LEFT JOIN PAYMENTS P2 ON P2.RECEIPT=R.ID AND P2.PAYMENTTYPE='AMEX'
	LEFT JOIN PAYMENTS P3 ON P3.RECEIPT=R.ID AND P3.PAYMENT='Cheque'
	LEFT JOIN PAYMENTS P4 ON P4.RECEIPT=R.ID AND P4.PAYMENT='Staff'
	LEFT JOIN PAYMENTS P5 ON P5.RECEIPT=R.ID AND P5.PAYMENT='Complementary'
	LEFT JOIN PAYMENTS P6 ON P6.RECEIPT=R.ID AND P6.PAYMENT='Voucher' 
	LEFT JOIN PAYMENTS P7 ON P7.RECEIPT=R.ID AND P7.PAYMENT='Mobile'
	LEFT JOIN PAYMENTS P8 ON P8.RECEIPT=R.ID AND P8.PAYMENT='Vcloud'  
	LEFT JOIN PAYMENTS P9 ON P9.RECEIPT=R.ID AND P9.PAYMENTTYPE='Food Panda'
	LEFT JOIN PAYMENTS P10 ON P10.RECEIPT=R.ID AND P10.PAYMENTTYPE='Swiggy'
	LEFT JOIN PAYMENTS P11 ON P11.RECEIPT=R.ID AND P11.PAYMENTTYPE='Delivery'
	LEFT JOIN PAYMENTS P12 ON P12.RECEIPT=R.ID AND P12.PAYMENTTYPE='Visa'
	LEFT JOIN PAYMENTS P13 ON P13.RECEIPT=R.ID AND P13.PAYMENTTYPE='Others'
	LEFT JOIN PAYMENTS P14 ON P14.RECEIPT=R.ID AND P14.PAYMENTTYPE='Zomato'
	LEFT JOIN TICKETS TK ON TK.ID=R.ID 
	LEFT JOIN TICKETLINES TL ON TK.ID=TL.TICKET 
	LEFT JOIN PRODUCTS AS PR1 ON PR1.ID = TL.PRODUCT 
	LEFT JOIN CATEGORIES C ON C.ID=PR1.CATEGORY
	LEFT JOIN CATEGORIES C1 ON C1.ID=C.PARENTID
	LEFT JOIN PEOPLE P ON P.ID=TK.PERSON
	LEFT JOIN PLACES PL ON PL.ID=TK.TABLEID
	LEFT JOIN FLOORS F ON F.ID=PL.FLOOR
	LEFT JOIN billwiseswachbharattax_view SW ON R.ID=SW.ID 
        LEFT JOIN billwiseservicetax_view ST ON R.ID=ST.ID
        LEFT JOIN billwisevattax_view VT ON R.ID=VT.ID
        LEFT JOIN billwiseservicecharge_view SC ON R.ID=SC.ID
        LEFT JOIN billwisekrishikalyantax_view KT ON R.ID=KT.ID
	WHERE TK.ISCANCELTICKET='N' 
	GROUP BY F.NAME,R.ID,DATE_FORMAT(R.DATENEW, '%Y-%M-%D')
	ORDER BY F.NAME,BILLNO,R.DATENEW;

